baseURL = "https://jorgeancal.com/"
languageCode = "en"
title = "The Green Notebook"
theme = "minimal"
googleAnalytics = "UA-108421112-1"
publishDir="docs"

[params]
    avatar = "/images/avatar.png"
    author = "Jorge Andreu Calatayud"
    description = "Hi, My name is Jorge Andreu Calatayud and sorry for my English. I’m an IT Engineer. I studied a Bachelor of Science in Business Information Technology, with University of Wales."
    info = "IT Engineer"
    githubUsername = "jorgeancal"
    pagesToShowInTheBeginningOfThePageable = 1
    pagesInTheMiddle = 1
    addPagesToShowInTheMiddle = 1
    pageMin = 1
    accent = "gren"
    paginate = 3
    showBorder = true
    backgroundColor = "white"
    ico = "/images/j.png"
    font = "Raleway" # should match the name on Google Fonts!
    mathJax = true
    highlight = false
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "java", "bash"]
    copyright = "@jorgeancal | Jorge Andreu Calatayud"
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about-me/"
    name = "About me"
    weight = 2

[[menu.main]]
    url = "/about-this-site/"
    name = "About This Site"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/jorgeancal/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/jorgeancal/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/jorgeancal/"
    name = "linkedin"
    weight = 3
[[menu.icon]]
    url = "https://www.instagram.com/jorgeancal/"
    name = "instagram"
    weight = 4

#[[menu.icon]]
    #url = "https://www.stackoverflow.com/username/"
    #name = "stack-overflow"
    #weight = 4
